# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  before_all do
    clean
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build in debug mode"
  lane :build_debug do
    gradle(
      task: "assemble",
      build_type: "Debug"
    )
  end

  desc "Build in release mode"
  lane :build_release do
    gradle(
      task: "bundle",
      build_type: "Release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" =>  ENV["KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["UPLOAD_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["UPLOAD_KEY_PASSWORD"],
      }
    )
  end

  desc 'Build the app'
  lane :build do |options|
    if options[:target] == "dev"
      build_debug
    elsif options[:target] == "release"
      build_release
    else
      puts "Unrecognized build target: #{options[:target]}. Valid ones are: dev, release."
    end
  end

  desc "Clean the build directory"
  lane :clean do
    gradle(
      task: "clean"
    )
  end
end
